export const weeklyCampaign = [
  {
    id: "1",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 10,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 12,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 13,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "13",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "14",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "15",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];

export const hotCampaign = [
  {
    id: "1",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 15,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "13",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "14",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "15",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];
