export const weeklyCampaign = [
  {
    id: "1",
    name: "Đà Lạt - Hồ Chí Minh Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 10,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 12,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 13,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "13",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "14",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "15",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];

export const hotCampaign = [
  {
    id: "1",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 15,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "13",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "14",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "15",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];

export const page1 = [
  {
    id: "1",
    name: "Trang 1 nèAAAAAAAAAAAAAAAAA",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 15,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];
export const page2 = [
  {
    id: "1",
    name: "Trang 2 nè",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 15,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];

export const page3 = [
  {
    id: "1",
    name: "Trang 3 nè",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "2",
    name: "Đà Lạt - Bình Phước",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Phước",
  },
  {
    id: "3",
    name: "Đà Lạt - Bình Dương",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 16,
    isActive: true,
    from: "Đà Lạt",
    to: "Bình Dương",
  },
  {
    id: "4",
    name: "Đà Lạt - Hải Phòng",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hải Phòng",
  },
  {
    id: "5",
    name: "Đà Lạt - Hà Nội",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hà Nội",
  },
  {
    id: "6",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 15,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "7",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 14,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "8",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "9",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 18,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "10",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 17,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "11",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 19,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
  {
    id: "12",
    name: "Đà Lạt - Hồ Chí Minh",
    description: "Đây là chiến dịch hằng tuần đi từ Đà Lạt về Hồ Chí Minh",
    image: "img/item/1.jpg",
    startDate: "20/12/2020",
    endDate: "24/12/2020",
    slot: 20,
    farmJoined: 20,
    isActive: true,
    from: "Đà Lạt",
    to: "Hồ Chí Minh",
  },
];

export const productsList = [{
  id: "1",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "2",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "3",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "4",
  name: "Hồng giòn Đà Lạt",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "5",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "6",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "7",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "8",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "9",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "10",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "11",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
{
  id: "12",
  name: "Hồng giòn",
  maxQuantity: 20,
  available: 100,
  farmName: "Nguyễn Thành Nhân'Farm",
  farmId: "1",
  campaignName: "Đà Lạt - Hồ Chí Minh",
  campaignIf: "1",
  price: 100000,
  unit: "kg",

},
]

export const page1_farm = [
  {
    id: "1",
    name:  "Page 1 Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "2",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "3",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "4",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "5",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "6",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "7",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "8",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "9",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "10",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "11",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "12",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  }
]

export const page2_farm = [
  {
    id: "1",
    name:  "Page 2 Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "2",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "3",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "4",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "5",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "6",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "7",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "8",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "9",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "10",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "11",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "12",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  }
]

export const page3_farm = [
  {
    id: "1",
    name:  "Page 3 Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "2",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "3",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "4",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "5",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "6",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "7",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "8",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  },
  {
    id: "9",
    name:  "Đà Lạt Milk Farm",
    address: "Thôn Cầu Sắt, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Nguyễn Thành nhân",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Đến mùa xuân, hoa mai anh đào Đà Lạt nở bung với màu sắc rực rỡ. Đến mùa thu thì những bông hoa Dã Quỳ vàng rực khoe sắc",
    status: "true"
  },
  {
    id: "10",
    name:  "Vinamilk Organic Milk",
    address: "Thôn Lạc Trường, xã Tu Tra, huyện Đơn Dương, Lâm Đồng",
    owner: "Lâm Minh Thìn",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Vinamilk Organic Milk tự hào khi có một trang trại bò sữa chuẩn organic châu Âu đầu tiên tại Việt Nam do tổ chức Control Union (Hà Lan) chứng nhận",
    status: "true"
  },
  {
    id: "11",
    name:  "Sunny Farm",
    address: "Dốc số 7, phường 11, Đà Lạt, Lâm Đồng",
    owner: "Nguyễn Xuân Linh Tâm",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Nông trại vui vẻ, hay còn được gọi với cái tên là Sunny Farm. Đây là một trong những nông trại Đà Lạt gây ấn tượng bởi cách trang trí và màu sắc dễ thương, bắt mắt. Đây cũng chính là điểm cộng khiến Sunny Farm trở nên thu hút hơn so với các nông trại khác.",
    status: "true"
  },
  {
    id: "12",
    name:  "Cầu Đất Farm",
    address: "Thôn Cầu Đất, xã Xuân Trường, phường 12, Đà Lạt",
    owner: "Nguyễn Quốc Vương",
    phone: "012345678",
    email: "farm1@gmail.com",
    area: "1",
    description: "Cầu Đất Farm là nông trại Đà Lạt nổi tiếng hấp dẫn bất kỳ ai mỗi khi đi du lịch thành phố ngàn hoa. Nơi đây nổi tiếng là nông trại trồng chè và cà phê nổi tiếng luôn. Với diện tích lên tới 220 ha, đồi chè Cầu Đất là địa điểm checkin hoành tráng đáng đồng tiền bát gạo tại Đà Lạt.",
    status: "true"
  }
]

export const page1_product = [
  {
    id: "1",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn page1",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "2",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "3",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "4",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "5",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "6",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "7",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "8",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "9",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "10",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "11",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "12",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  }
]

export const page2_product = [
  {
    id: "1",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn page2",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "2",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "3",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "4",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "5",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "6",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "7",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "8",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "9",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "10",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "11",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "12",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  }
]

export const page3_product = [
  {
    id: "1",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn page3",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "2",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "3",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "4",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "5",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "6",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "7",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "8",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "9",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "10",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "11",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  },
  {
    id: "12",
    image: "/img/item/3.jpg",
    farmName: "Nguyễn Thành Nhân",
    campaignName: "Đà Lạt - Hồ Chí Minh",
    productName: "Hồng giòn Đà Lạt",
    productDescription: "Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn.",
    price: 100000,
    unit: "kg",
    available: 100,
    maxQuantity: 120,
    harverst: "20/11/2020",
    harverstesdcription: "Gieo trồng trong mùa vụ đầu tiên của năm 2020 Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn. Đây là Hồng giòn đà lạt được trồng trong nông trại theo tiêu chuẩn VietGap, đảm bảo chất lượng. Hồng được thu hoạch đúng mùa vụ nên đảm bảo chín giòn."
  }
]
